//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
#pragma warning disable 1591

namespace Company.UiPath.DocumentOcr.Activities.Resources
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PublicResXFileCodeGenerator", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager? resourceMan;

        private static global::System.Globalization.CultureInfo? resourceCulture;

        /// <summary>
        ///   Initializes a new instance of the <see cref="Resources"/> class.
        /// </summary>
        public Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan is null)
                {
                    resourceMan = new global::System.Resources.ResourceManager(
                        "Company.UiPath.DocumentOcr.Activities.Resources.Resources",
                        typeof(Resources).Assembly);
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all resource lookups using this strongly typed resource class.
        /// </summary>
        public static global::System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string DocumentOcr_Category => ResourceManager.GetString("DocumentOcr_Category", resourceCulture)!;

        public static string Input_Category => ResourceManager.GetString("Input_Category", resourceCulture)!;

        public static string Advanced_Category => ResourceManager.GetString("Advanced_Category", resourceCulture)!;

        public static string Output_Category => ResourceManager.GetString("Output_Category", resourceCulture)!;

        public static string ExtractTextFromDocument_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_Description => ResourceManager.GetString("ExtractTextFromDocument_Description", resourceCulture)!;

        public static string ExtractTextFromDocument_FilePath_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_FilePath_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_FilePath_Description => ResourceManager.GetString("ExtractTextFromDocument_FilePath_Description", resourceCulture)!;

        public static string ExtractTextFromDocument_Language_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_Language_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_Language_Description => ResourceManager.GetString("ExtractTextFromDocument_Language_Description", resourceCulture)!;

        public static string ExtractTextFromDocument_PdfScale_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_PdfScale_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_PdfScale_Description => ResourceManager.GetString("ExtractTextFromDocument_PdfScale_Description", resourceCulture)!;

        public static string ExtractTextFromDocument_MaximumPages_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_MaximumPages_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_MaximumPages_Description => ResourceManager.GetString("ExtractTextFromDocument_MaximumPages_Description", resourceCulture)!;

        public static string ExtractTextFromDocument_MaximumFileSizeMb_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_MaximumFileSizeMb_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_MaximumFileSizeMb_Description => ResourceManager.GetString("ExtractTextFromDocument_MaximumFileSizeMb_Description", resourceCulture)!;

        public static string ExtractTextFromDocument_EnablePreprocessing_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_EnablePreprocessing_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_EnablePreprocessing_Description => ResourceManager.GetString("ExtractTextFromDocument_EnablePreprocessing_Description", resourceCulture)!;

        public static string ExtractTextFromDocument_ExtractedText_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_ExtractedText_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_ExtractedText_Description => ResourceManager.GetString("ExtractTextFromDocument_ExtractedText_Description", resourceCulture)!;

        public static string ExtractTextFromDocument_PageCount_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_PageCount_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_PageCount_Description => ResourceManager.GetString("ExtractTextFromDocument_PageCount_Description", resourceCulture)!;

        public static string ExtractTextFromDocument_Confidence_DisplayName => ResourceManager.GetString("ExtractTextFromDocument_Confidence_DisplayName", resourceCulture)!;

        public static string ExtractTextFromDocument_Confidence_Description => ResourceManager.GetString("ExtractTextFromDocument_Confidence_Description", resourceCulture)!;
    }
}

#pragma warning restore 1591
