import type { RunContext } from "../testing/run-context.js";
import type { PageSnapshot } from "../types/testing.js";
import { redactSecrets } from "../security/secret-redaction.js";

export class AiContextBuilder {
  build(context: RunContext, snapshot: PageSnapshot): unknown {
    return redactSecrets({
      runId: context.runId,
      targetOrigin: context.targetOrigin,
      role: context.roleName,
      viewport: context.viewportName,
      locale: context.localeName,
      direction: context.direction,
      selectedTestingTypes: context.request.testTypes,
      previousPageSummaries: context.previousPageSummaries.slice(-20),
      previousTestResults: context.previousTestResults.slice(-50),
      knownWorkflows: context.knownWorkflows,
      visitedUrls: [...context.visitedUrls],
      existingGeneratedTestEntities: context.generatedEntities,
      safetyRestrictions: context.request.execution,
      remainingPageBudget: context.request.crawl.maxPages - context.visitedUrls.size,
      remainingActionBudgetPerPage: context.request.execution.maximumActionsPerPage,
      pageSnapshot: {
        url: snapshot.url,
        canonicalUrl: snapshot.canonicalUrl,
        title: snapshot.title,
        headings: snapshot.headings,
        visibleText: snapshot.visibleText.slice(0, 6000),
        queryParameters: snapshot.currentQueryParameters,
        links: snapshot.links.slice(0, 120).map((link) => ({
          text: link.text,
          href: link.href,
          canonicalHref: link.canonicalHref,
          internal: link.internal,
          sourceElementId: link.sourceElementId,
        })),
        images: snapshot.images.slice(0, 80),
        scripts: snapshot.scripts.slice(0, 80),
        forms: snapshot.forms.map((form) => ({
          elementId: form.elementId,
          implicit: form.implicit,
          method: form.method,
          action: form.action,
          apparentPurpose: form.apparentPurpose,
          fields: form.fields.map((field) => ({
            id: field.id,
            kind: field.kind,
            label: field.label,
            placeholder: field.placeholder,
            name: field.name,
            type: field.type,
            required: field.required,
            disabled: field.disabled,
            hidden: field.hidden,
            validation: field.validation,
            locator: field.locator,
          })),
          submitControls: form.submitControls.map((control) => ({
            id: control.id,
            kind: control.kind,
            text: control.text,
            accessibleName: control.accessibleName,
            disabled: control.disabled,
            hidden: control.hidden,
            locator: control.locator,
          })),
        })),
        elements: snapshot.elements.slice(0, 200).map((element) => ({
          id: element.id,
          kind: element.kind,
          tagName: element.tagName,
          role: element.role,
          accessibleName: element.accessibleName,
          text: element.text,
          label: element.label,
          placeholder: element.placeholder,
          name: element.name,
          type: element.type,
          disabled: element.disabled,
          hidden: element.hidden,
          required: element.required,
          formOwnerElementId: element.formOwnerElementId,
          locator: element.locator,
        })),
        tables: snapshot.tables.slice(0, 10),
        dialogs: snapshot.dialogs,
        consoleErrors: snapshot.consoleErrors,
        failedRequests: snapshot.failedRequests,
        observedApiCalls: snapshot.observedApiCalls,
        visibleValidationErrors: snapshot.visibleValidationErrors,
        uiObservations: snapshot.uiObservations,
      },
    });
  }
}
