export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  AUTHORIZATION_CONFIRMATION_MISSING: "AUTHORIZATION_CONFIRMATION_MISSING",
  UNSAFE_TARGET: "UNSAFE_TARGET",
  DNS_RESOLUTION_FAILURE: "DNS_RESOLUTION_FAILURE",
  BROWSER_LAUNCH_FAILURE: "BROWSER_LAUNCH_FAILURE",
  NAVIGATION_FAILURE: "NAVIGATION_FAILURE",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  HUMAN_AUTHENTICATION_REQUIRED: "HUMAN_AUTHENTICATION_REQUIRED",
  CRAWL_LIMIT_REACHED: "CRAWL_LIMIT_REACHED",
  RUN_TIMEOUT: "RUN_TIMEOUT",
  AI_REQUEST_FAILURE: "AI_REQUEST_FAILURE",
  INVALID_AI_RESPONSE: "INVALID_AI_RESPONSE",
  AI_PLANNING_LIMIT_REACHED: "AI_PLANNING_LIMIT_REACHED",
  ACTION_BLOCKED_BY_POLICY: "ACTION_BLOCKED_BY_POLICY",
  ELEMENT_NO_LONGER_AVAILABLE: "ELEMENT_NO_LONGER_AVAILABLE",
  ASSERTION_FAILURE: "ASSERTION_FAILURE",
  PAGE_CRASH: "PAGE_CRASH",
  REPORT_GENERATION_FAILURE: "REPORT_GENERATION_FAILURE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const LLM_FAILURE_REASONS = {
  LLM_TRANSPORT_ERROR: "llm_transport_error",
  LLM_RATE_LIMITED: "llm_rate_limited",
  LLM_INVALID_JSON: "llm_invalid_json",
  LLM_SCHEMA_INVALID: "llm_schema_invalid",
  LLM_TRUNCATED: "llm_truncated",
  LLM_UNAVAILABLE: "llm_unavailable",
} as const;

export type LlmFailureReason = (typeof LLM_FAILURE_REASONS)[keyof typeof LLM_FAILURE_REASONS];

export interface LlmAttempt {
  model: string;
  reason: LlmFailureReason;
  message: string;
}
